### ISSUE TITLE
null text being shown for description in website

### ISSUE THREAD

**Issue by PauloPhagula** [ntxuva/ntxuva-7.x-1.0-beta2#2]
When browsing the site the text _null_ is being shown for some of the reports as can be seen in the screenshot bellow.

![screen shot 2015-07-21 at 11 05 18 am](https://cloud.githubusercontent.com/assets/6130991/8796845/275ee7fc-2f98-11e5-81c2-469276c6b558.png)

**Comment by ghost** [comment]
This is an issue on the USSD side that is not including any description in
the requests created via the Open311 API, not a problem with Ntxuva.

Being solved at the moment with Valter.

Jean Barroca

**Comment by PauloPhagula** [comment]
Issue has been solved and API is showing all required info
