### ISSUE TITLE
API requests don't have the address details filled

### ISSUE THREAD

**Issue by PauloPhagula** [ntxuva/ntxuva-7.x-1.0-beta2#3]
Hi all,

Some requests returned from the [API endpoint http://mopa.co.mz/georeport/v2/](http://mopa.co.mz/georeport/v2/) don't have the address details filled. For instance the requests bellow differ as the first one contains only the _latitude_ and _longitude_ fields, but no _address_, whilst the last one has all of them.

``` JSON
{
        "agency_responsible": "DMGRSUS",
        "description": "null",
        "lat": -25.8283,
        "long": 32.6008,
        "requested_datetime": "2015-07-03T16:46:36+02:00",
        "service_code": "04",
        "service_name": "Tchova n\u00e3o passou",
        "service_notice": "Registado",
        "service_request_id": "1527638",
        "status": "open",
        "updated_datetime": "2015-07-03T16:46:36+02:00",
        "zipcode": null
    },
```

``` JSON
{
        "address": "Avenida Acordos de Lusaka,  Urbaniza\u00e7\u00e3o, Distrito Urbano de KaMaxaquene, Cidade de Maputo",
        "agency_responsible": "DMGRSUS",
        "lat": -25.94176033042,
        "long": 32.579076290131,
        "media_url": "http://mopa.co.mz/sites/default/files/IMG_20150702_131018.jpg",
        "neighbourhood": "Urbaniza\u00e7\u00e3o, Distrito Urbano de KaMaxaquene",
        "requested_datetime": "2015-07-02T13:23:17+02:00",
        "service_code": "01",
        "service_name": "Cami\u00e3o n\u00e3o recolheu o contentor",
        "service_notice": "Registado",
        "service_request_id": "1527637",
        "status": "open",
        "updated_datetime": "2015-07-02T13:23:17+02:00",
        "zipcode": null
    },
```

I have interest in having the _address_ filled in all requests as this information is required in to produce the daily report sent to the municipal authorities. Bellow is a sample of one of these reports and we can see that the _district_ and _neighborhood_ fields are empty due to this.
<img width="872" alt="screen shot 2015-07-21 at 11 26 16 am" src="https://cloud.githubusercontent.com/assets/6130991/8797394/594e72b6-2f9b-11e5-8989-a8980ae0321a.png">

Finally, I'd like to request this issue to be fixed or alternatively be provided and additional API endpoint whereby I could get the _district_ and _neighborhood_ based on the _latitude_ and _longitude_.

**Comment by ghost** [comment]
You'll have the information you need on the location_id field according to
ntxuva locations' API:

https://docs.google.com/document/d/1oTCFb_mOc9W_t90c6eFwG3TcMSh8vzAq3Qi_7rkoe0g/edit?usp=sharing

Being changed on the USSD code by Valter.

Jean Barroca

**Comment by PauloPhagula** [comment]
Change has been implemented and information is being used.
